---
# handlers file for sbaerlocher.redis

- name: restart redis
  service:
    name: "{{ redis_service }}"
    state: restarted

- name: started redis
  service:
    name: "{{ redis_service }}"
    state: started

- name: enabled redis
  service:
    name: "{{ redis_service }}"
    enabled: true
